---
extends: default

rules:
  comments: enable
  line-length: disable

# NOTE: These files are Jinja2 templates. Therefore they are ignored.
ignore: |
  ansible-collection-role/meta.yml
  ansible-collection/meta.yml
