---
extends: default

rules:
  line-length: disable
  truthy: disable

# NOTE: These files are Jinja2 templates. Therefore they are ignored.
ignore: |
  ansible/.travis.yml
  ansible/meta.yml
  docker/.travis.yml
  molecule/molecule.yml
