---
name: Check ansible syntax

"on":
  push:
    paths:
      - .github/workflows/check-ansible-syntax.yml
      - '**.yml'
  pull_request:
    paths:
      - .github/workflows/check-ansible-syntax.yml
      - '**.yml'

jobs:
  check-ansible-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
