---
name: Update generics

"on":
  push:
    paths:
      - .github/workflows/update-generics.yml
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [update-generics]

jobs:
  update-generics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip3 install python-gilt jinja2
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            gilt overlay
            gilt overlay
          COMMIT_EMAIL: github+actions@osism.de
          COMMIT_MESSAGE: |
            chore: udpate generics

            Signed-off-by: GitHub Actions <github+actions@osism.de>
          COMMIT_NAME: GitHub Actions
          ONLY_DEFAULT_BRANCH: true
          PR_BRANCH_NAME: update-generics
          PR_BRANCH_PREFIX: chore/
          PR_TITLE: 'chore: update generics'
