---
galaxy_info:
  author: Christian Berendt
  description: Role osism.{{ ansible_collection_name }}.{{ ansible_role_name }}
  company: Betacloud Solutions GmbH
  license: Apache License 2.0
  min_ansible_version: {{ releases|first }}
  platforms:
    - name: Ubuntu
      versions:
{%- for distribution in distributions|sort %}
        - {{ distribution }}
{%- endfor %}
  galaxy_tags:
    - system
dependencies: []
